package com.zylr.minescapeaddons.addons.gui.widgets.menus.items;

public enum BypassItems {

    POTION("POTION"),
    ANTI_VENOM("ANTI-VENOM"),
    ANTIDOTE("ANTIDOTE"),
    ANTIFIRE_POTION("ANTIFIRE POTION"),
    ANTIPOISON("ANTIPOISON"),
    EXTENDED_ANTIFIRE("EXTENDED ANTIFIRE"),
    EXTENDED_SUPER_ANTIFIRE("EXTENDED SUPER ANTIFIRE"),
    SUPER_ANTFIRE("SUPER ANTIFIRE"),
    SUPER_ANTIPOISON("SUPER ANTIPOISON"),
    BREW("BREW"),
    BLAMISH_OIL("BLAMISH OIL"),
    GUTHIX_BALANCE("GUTHIX BALANCE"),
    GUTHIX_REST_TEA("GUTHIX REST TEA"),
    IMP_REPELLENT("IMP REPELLENT"),
    MAGIC_ESSENCE("MAGIC ESSENCE"),
    MENAPHITE_REMEDY("MENAPHITE REMEDY"),
    RELICYMS_BALM("RELICYM'S BALM"),
    SANFEW_SERUM("SANFEW SERUM"),
    SARADOMIN_BREW("SARADOMIN BREW"),
    SERUM_207("SERUM 207"),
    SRHINK_ME_QUICK("SRHINK-ME-QUICK"),
    SUPER_ATTACK("SUPER ATTACK"),
    SUPER_DEFENCE("SUPER DEFENCE"),
    SUPER_ENERGY("SUPER ENERGY"),
    SUPER_RESTORE("SUPER RESTORE"),
    SUPER_STRENGTH("SUPER STRENGTH"),
    WEAPON_POISON("WEAPON POISON"),
    ZAMORAK_BREW("ZAMORAK BREW");

    public static final String menuTitle = "Bypass Items";
    private final String name;
    BypassItems(String name) {
        this.name = name;
    }
    public String getName() { return this.name; }
}
