package com.zylr.client.items;

import com.zylr.client.items.armor.AbstractArmorItem;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.equipment.ArmorType;

public enum OverrideArmors {
    DRAGON_PLATEBODY(ModItems.DRAGON_ARMOR.get(ArmorType.CHESTPLATE), "dragon platebody"),
    DRAGON_PLATELEGS(ModItems.DRAGON_ARMOR.get(ArmorType.LEGGINGS), "dragon platelegs"),
    DRAGON_PLATESKIRT(ModItems.DRAGON_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "dragon plateskirt"),
    DRAGON_BOOTS(ModItems.DRAGON_ARMOR.get(ArmorType.BOOTS), "dragon boots"),

    BRONZE_CHAINBODY(ModItems.BRONZE_CHAINBODY.get(ArmorType.CHESTPLATE), "bronze chainbody"),
    BRONZE_PLATEBODY(ModItems.BRONZE_ARMOR.get(ArmorType.CHESTPLATE), "bronze platebody"),
    BRONZE_PLATELEGS(ModItems.BRONZE_ARMOR.get(ArmorType.LEGGINGS), "bronze platelegs"),
    BRONZE_PLATESKIRT(ModItems.BRONZE_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "bronze plateskirt"),
    BRONZE_PLATEBODY_T(ModItems.BRONZE_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "bronze platebody(t)"),
    BRONZE_PLATELEGS_T(ModItems.BRONZE_ARMOR_TRIM.get(ArmorType.LEGGINGS), "bronze platelegs(t)"),
    BRONZE_PLATESKIRT_T(ModItems.BRONZE_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "bronze plateskirt(t)"),
    BRONZE_PLATEBODY_G(ModItems.BRONZE_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "bronze platebody(g)"),
    BRONZE_PLATELEGS_G(ModItems.BRONZE_ARMOR_GOLD.get(ArmorType.LEGGINGS), "bronze platelegs(g)"),
    BRONZE_PLATESKIRT_G(ModItems.BRONZE_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "bronze plateskirt(g)"),
    BRONZE_BOOTS(ModItems.BRONZE_ARMOR.get(ArmorType.BOOTS), "bronze boots"),

    IRON_CHAINBODY(ModItems.IRON_CHAINBODY.get(ArmorType.CHESTPLATE), "iron chainbody"),
    IRON_PLATEBODY(ModItems.IRON_ARMOR.get(ArmorType.CHESTPLATE), "iron platebody"),
    IRON_PLATELEGS(ModItems.IRON_ARMOR.get(ArmorType.LEGGINGS), "iron platelegs"),
    IRON_PLATESKIRT(ModItems.IRON_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "iron plateskirt"),
    IRON_PLATEBODY_T(ModItems.IRON_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "iron platebody(t)"),
    IRON_PLATELEGS_T(ModItems.IRON_ARMOR_TRIM.get(ArmorType.LEGGINGS), "iron platelegs(t)"),
    IRON_PLATESKIRT_T(ModItems.IRON_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "iron plateskirt(t)"),
    IRON_PLATEBODY_G(ModItems.IRON_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "iron platebody(g)"),
    IRON_PLATELEGS_G(ModItems.IRON_ARMOR_GOLD.get(ArmorType.LEGGINGS), "iron platelegs(g)"),
    IRON_PLATESKIRT_G(ModItems.IRON_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "iron plateskirt(g)"),
    IRON_BOOTS(ModItems.IRON_ARMOR.get(ArmorType.BOOTS), "iron boots"),

    STEEL_CHAINBODY(ModItems.STEEL_CHAINBODY.get(ArmorType.CHESTPLATE), "steel chainbody"),
    STEEL_PLATEBODY(ModItems.STEEL_ARMOR.get(ArmorType.CHESTPLATE), "steel platebody"),
    STEEL_PLATELEGS(ModItems.STEEL_ARMOR.get(ArmorType.LEGGINGS), "steel platelegs"),
    STEEL_PLATESKIRT(ModItems.STEEL_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "steel plateskirt"),
    STEEL_PLATEBODY_T(ModItems.STEEL_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "steel platebody(t)"),
    STEEL_PLATELEGS_T(ModItems.STEEL_ARMOR_TRIM.get(ArmorType.LEGGINGS), "steel platelegs(t)"),
    STEEL_PLATESKIRT_T(ModItems.STEEL_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "steel plateskirt(t)"),
    STEEL_PLATEBODY_G(ModItems.STEEL_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "steel platebody(g)"),
    STEEL_PLATELEGS_G(ModItems.STEEL_ARMOR_GOLD.get(ArmorType.LEGGINGS), "steel platelegs(g)"),
    STEEL_PLATESKIRT_G(ModItems.STEEL_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "steel plateskirt(g)"),
    STEEL_BOOTS(ModItems.STEEL_ARMOR.get(ArmorType.BOOTS), "steel boots"),

    BLACK_CHAINBODY(ModItems.BLACK_CHAINBODY.get(ArmorType.CHESTPLATE), "black chainbody"),
    BLACK_PLATEBODY(ModItems.BLACK_ARMOR.get(ArmorType.CHESTPLATE), "black platebody"),
    BLACK_PLATELEGS(ModItems.BLACK_ARMOR.get(ArmorType.LEGGINGS), "black platelegs"),
    BLACK_PLATESKIRT(ModItems.BLACK_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "black plateskirt"),
    BLACK_PLATEBODY_T(ModItems.BLACK_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "black platebody(t)"),
    BLACK_PLATELEGS_T(ModItems.BLACK_ARMOR_TRIM.get(ArmorType.LEGGINGS), "black platelegs(t)"),
    BLACK_PLATESKIRT_T(ModItems.BLACK_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "black plateskirt(t)"),
    BLACK_PLATEBODY_G(ModItems.BLACK_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "black platebody(g)"),
    BLACK_PLATELEGS_G(ModItems.BLACK_ARMOR_GOLD.get(ArmorType.LEGGINGS), "black platelegs(g)"),
    BLACK_PLATESKIRT_G(ModItems.BLACK_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "black plateskirt(g)"),
    BLACK_BOOTS(ModItems.BLACK_ARMOR.get(ArmorType.BOOTS), "black boots"),

    WHITE_CHAINBODY(ModItems.WHITE_CHAINBODY.get(ArmorType.CHESTPLATE), "white chainbody"),
    WHITE_PLATEBODY(ModItems.WHITE_ARMOR.get(ArmorType.CHESTPLATE), "white platebody"),
    WHITE_PLATELEGS(ModItems.WHITE_ARMOR.get(ArmorType.LEGGINGS), "white platelegs"),
    WHITE_BOOTS(ModItems.WHITE_ARMOR.get(ArmorType.BOOTS), "white boots"),

    MITRHIL_CHAINBODY(ModItems.MITHRIL_CHAINBODY.get(ArmorType.CHESTPLATE), "mithril chainbody"),
    MITHRIL_PLATEBODY(ModItems.MITHRIL_ARMOR.get(ArmorType.CHESTPLATE), "mithril platebody"),
    MITHRIL_PLATELEGS(ModItems.MITHRIL_ARMOR.get(ArmorType.LEGGINGS), "mithril platelegs"),
    MITHRIL_PLATESKIRT(ModItems.MITHRIL_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "mithril plateskirt"),
    MITHRIL_PLATEBODY_T(ModItems.MITHRIL_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "mithril platebody(t)"),
    MITHRIL_PLATELEGS_T(ModItems.MITHRIL_ARMOR_TRIM.get(ArmorType.LEGGINGS), "mithril platelegs(t)"),
    MITHRIL_PLATESKIRT_T(ModItems.MITHRIL_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "mithril plateskirt(t)"),
    MITHRIL_PLATEBODY_G(ModItems.MITHRIL_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "mithril platebody(g)"),
    MITHRIL_PLATELEGS_G(ModItems.MITHRIL_ARMOR_GOLD.get(ArmorType.LEGGINGS), "mithril platelegs(g)"),
    MITHRIL_PLATESKIRT_G(ModItems.MITHRIL_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "mithril plateskirt(g)"),
    MITHRIL_BOOTS(ModItems.MITHRIL_ARMOR.get(ArmorType.BOOTS), "mithril boots"),

    ADAMANT_CHAINBODY(ModItems.ADAMANT_CHAINBODY.get(ArmorType.CHESTPLATE), "adamant chainbody"),
    ADAMANT_PLATEBODY(ModItems.ADAMANT_ARMOR.get(ArmorType.CHESTPLATE), "adamant platebody"),
    ADAMANT_PLATELEGS(ModItems.ADAMANT_ARMOR.get(ArmorType.LEGGINGS), "adamant platelegs"),
    ADAMANT_PLATESKIRT(ModItems.ADAMANT_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "adamant plateskirt"),
    ADAMANT_PLATEBODY_T(ModItems.ADAMANT_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "adamant platebody(t)"),
    ADAMANT_PLATELEGS_T(ModItems.ADAMANT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "adamant platelegs(t)"),
    ADAMANT_PLATESKIRT_T(ModItems.ADAMANT_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "adamant plateskirt(t)"),
    ADAMANT_PLATEBODY_G(ModItems.ADAMANT_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "adamant platebody(g)"),
    ADAMANT_PLATELEGS_G(ModItems.ADAMANT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "adamant platelegs(g)"),
    ADAMANT_PLATESKIRT_G(ModItems.ADAMANT_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "adamant plateskirt(g)"),
    ADAMANT_BOOTS(ModItems.ADAMANT_ARMOR.get(ArmorType.BOOTS), "adamant boots"),

    RUNE_CHAINBODY(ModItems.RUNE_CHAINBODY.get(ArmorType.CHESTPLATE), "rune chainbody"),
    RUNE_PLATEBODY(ModItems.RUNE_ARMOR.get(ArmorType.CHESTPLATE), "rune platebody"),
    RUNE_PLATELEGS(ModItems.RUNE_ARMOR.get(ArmorType.LEGGINGS), "rune platelegs"),
    RUNE_PLATESKIRT(ModItems.RUNE_PLATESKIRT_ARMOR.get(ArmorType.LEGGINGS), "rune plateskirt"),
    RUNE_PLATEBODY_T(ModItems.RUNE_ARMOR_TRIM.get(ArmorType.CHESTPLATE), "rune platebody(t)"),
    RUNE_PLATELEGS_T(ModItems.RUNE_ARMOR_TRIM.get(ArmorType.LEGGINGS), "rune platelegs(t)"),
    RUNE_PLATESKIRT_T(ModItems.RUNE_PLATESKIRT_ARMOR_TRIM.get(ArmorType.LEGGINGS), "rune plateskirt(t)"),
    RUNE_PLATEBODY_G(ModItems.RUNE_ARMOR_GOLD.get(ArmorType.CHESTPLATE), "rune platebody(g)"),
    RUNE_PLATELEGS_G(ModItems.RUNE_ARMOR_GOLD.get(ArmorType.LEGGINGS), "rune platelegs(g)"),
    RUNE_PLATESKIRT_G(ModItems.RUNE_PLATESKIRT_ARMOR_GOLD.get(ArmorType.LEGGINGS), "rune plateskirt(g)"),
    RUNE_BOOTS(ModItems.RUNE_ARMOR.get(ArmorType.BOOTS), "rune boots"),

    GUTHANS_PLATEBODY(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthan's platebody"),
    GUTHANS_PLATELEGS(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthan's chainskirt"),
    GUTHANS_PLATEBODY_100(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthan's platebody 100"),
    GUTHANS_PLATELEGS_100(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthan's chainskirt 100"),
    GUTHANS_PLATEBODY_75(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthan's platebody 75"),
    GUTHANS_PLATELEGS_75(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthan's chainskirt 75"),
    GUTHANS_PLATEBODY_50(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthan's platebody 50"),
    GUTHANS_PLATELEGS_50(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthan's chainskirt 50"),
    GUTHANS_PLATEBODY_25(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthan's platebody 25"),
    GUTHANS_PLATELEGS_25(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthan's chainskirt 25"),

    AHRIMS_ROBETOP(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrim's robetop"),
    AHRIMS_ROBESKIRT(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrim's robeskirt"),
    AHRIMS_ROBETOP_100(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrim's robetop 100"),
    AHRIMS_ROBESKIRT_100(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrim's robeskirt 100"),
    AHRIMS_ROBETOP_75(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrim's robetop 75"),
    AHRIMS_ROBESKIRT_75(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrim's robeskirt 75"),
    AHRIMS_ROBETOP_50(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrim's robetop 50"),
    AHRIMS_ROBESKIRT_50(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrim's robeskirt 50"),
    AHRIMS_ROBETOP_25(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrim's robetop 25"),
    AHRIMS_ROBESKIRT_25(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrim's robeskirt 25"),

    DHAROKS_PLATEBODY(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharok's platebody"),
    DHAROKS_PLATELEGS(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharok's platelegs"),
    DHAROKS_PLATEBODY_100(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharok's platebody 100"),
    DHAROKS_PLATELEGS_100(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharok's platelegs 100"),
    DHAROKS_PLATEBODY_75(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharok's platebody 75"),
    DHAROKS_PLATELEGS_75(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharok's platelegs 75"),
    DHAROKS_PLATEBODY_50(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharok's platebody 50"),
    DHAROKS_PLATELEGS_50(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharok's platelegs 50"),
    DHAROKS_PLATEBODY_25(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharok's platebody 25"),
    DHAROKS_PLATELEGS_25(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharok's platelegs 25"),

    VERACS_PLATEBODY(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "verac's brassard"),
    VERACS_PLATELEGS(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "verac's plateskirt"),
    VERACS_PLATEBODY_100(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "verac's brassard 100"),
    VERACS_PLATELEGS_100(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "verac's plateskirt 100"),
    VERACS_PLATEBODY_75(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "verac's brassard 75"),
    VERACS_PLATELEGS_75(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "verac's plateskirt 75"),
    VERACS_PLATEBODY_50(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "verac's brassard 50"),
    VERACS_PLATELEGS_50(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "verac's plateskirt 50"),
    VERACS_PLATEBODY_25(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "verac's brassard 25"),
    VERACS_PLATELEGS_25(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "verac's plateskirt 25"),

    TORAGS_PLATEBODY(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torag's platebody"),
    TORAGS_PLATELEGS(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torag's platelegs"),
    TORAGS_PLATEBODY_100(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torag's platebody 100"),
    TORAGS_PLATELEGS_100(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torag's platelegs 100"),
    TORAGS_PLATEBODY_75(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torag's platebody 75"),
    TORAGS_PLATELEGS_75(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torag's platelegs 75"),
    TORAGS_PLATEBODY_50(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torag's platebody 50"),
    TORAGS_PLATELEGS_50(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torag's platelegs 50"),
    TORAGS_PLATEBODY_25(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torag's platebody 25"),
    TORAGS_PLATELEGS_25(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torag's platelegs 25"),

    KARILS_LEATHERTOP(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karil's leathertop"),
    KARILS_LEATHERSKIRT(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karil's leatherskirt"),
    KARILS_LEATHERTOP_100(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karil's leathertop 100"),
    KARILS_LEATHERSKIRT_100(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karil's leatherskirt 100"),
    KARILS_LEATHERTOP_75(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karil's leathertop 75"),
    KARILS_LEATHERSKIRT_75(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karil's leatherskirt 75"),
    KARILS_LEATHERTOP_50(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karil's leathertop 50"),
    KARILS_LEATHERSKIRT_50(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karil's leatherskirt 50"),
    KARILS_LEATHERTOP_25(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karil's leathertop 25"),
    KARILS_LEATHERSKIRT_25(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karil's leatherskirt 25"),

    // Temp Barrows names
    TEMP_GUTHANS_PLATEBODY(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthans platebody"),
    TEMP_GUTHANS_PLATELEGS(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthans chainskirt"),
    TEMP_GUTHANS_PLATEBODY_100(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthans platebody 100"),
    TEMP_GUTHANS_PLATELEGS_100(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthans chainskirt 100"),
    TEMP_GUTHANS_PLATEBODY_75(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthans platebody 75"),
    TEMP_GUTHANS_PLATELEGS_75(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthans chainskirt 75"),
    TEMP_GUTHANS_PLATEBODY_50(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthans platebody 50"),
    TEMP_GUTHANS_PLATELEGS_50(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthans chainskirt 50"),
    TEMP_GUTHANS_PLATEBODY_25(ModItems.GUTHANS_ARMOR.get(ArmorType.CHESTPLATE), "guthans platebody 25"),
    TEMP_GUTHANS_PLATELEGS_25(ModItems.GUTHANS_ARMOR.get(ArmorType.LEGGINGS), "guthans chainskirt 25"),

    TEMP_AHRIMS_ROBETOP(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrims robetop"),
    TEMP_AHRIMS_ROBESKIRT(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrims robeskirt"),
    TEMP_AHRIMS_ROBETOP_100(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrims robetop 100"),
    TEMP_AHRIMS_ROBESKIRT_100(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrims robeskirt 100"),
    TEMP_AHRIMS_ROBETOP_75(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrims robetop 75"),
    TEMP_AHRIMS_ROBESKIRT_75(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrims robeskirt 75"),
    TEMP_AHRIMS_ROBETOP_50(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrims robetop 50"),
    TEMP_AHRIMS_ROBESKIRT_50(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrims robeskirt 50"),
    TEMP_AHRIMS_ROBETOP_25(ModItems.AHRIMS_ARMOR.get(ArmorType.CHESTPLATE), "ahrims robetop 25"),
    TEMP_AHRIMS_ROBESKIRT_25(ModItems.AHRIMS_ARMOR.get(ArmorType.LEGGINGS), "ahrims robeskirt 25"),

    TEMP_DHAROKS_PLATEBODY(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharoks platebody"),
    TEMP_DHAROKS_PLATELEGS(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharoks platelegs"),
    TEMP_DHAROKS_PLATEBODY_100(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharoks platebody 100"),
    TEMP_DHAROKS_PLATELEGS_100(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharoks platelegs 100"),
    TEMP_DHAROKS_PLATEBODY_75(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharoks platebody 75"),
    TEMP_DHAROKS_PLATELEGS_75(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharoks platelegs 75"),
    TEMP_DHAROKS_PLATEBODY_50(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharoks platebody 50"),
    TEMP_DHAROKS_PLATELEGS_50(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharoks platelegs 50"),
    TEMP_DHAROKS_PLATEBODY_25(ModItems.DHAROKS_ARMOR.get(ArmorType.CHESTPLATE), "dharoks platebody 25"),
    TEMP_DHAROKS_PLATELEGS_25(ModItems.DHAROKS_ARMOR.get(ArmorType.LEGGINGS), "dharoks platelegs 25"),

    TEMP_VERACS_PLATEBODY(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "veracs brassard"),
    TEMP_VERACS_PLATELEGS(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "veracs plateskirt"),
    TEMP_VERACS_PLATEBODY_100(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "veracs brassard 100"),
    TEMP_VERACS_PLATELEGS_100(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "veracs plateskirt 100"),
    TEMP_VERACS_PLATEBODY_75(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "veracs brassard 75"),
    TEMP_VERACS_PLATELEGS_75(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "veracs plateskirt 75"),
    TEMP_VERACS_PLATEBODY_50(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "veracs brassard 50"),
    TEMP_VERACS_PLATELEGS_50(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "veracs plateskirt 50"),
    TEMP_VERACS_PLATEBODY_25(ModItems.VERACS_ARMOR.get(ArmorType.CHESTPLATE), "veracs brassard 25"),
    TEMP_VERACS_PLATELEGS_25(ModItems.VERACS_ARMOR.get(ArmorType.LEGGINGS), "veracs plateskirt 25"),

    TEMP_TORAGS_PLATEBODY(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torags platebody"),
    TEMP_TORAGS_PLATELEGS(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torags platelegs"),
    TEMP_TORAGS_PLATEBODY_100(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torags platebody 100"),
    TEMP_TORAGS_PLATELEGS_100(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torags platelegs 100"),
    TEMP_TORAGS_PLATEBODY_75(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torags platebody 75"),
    TEMP_TORAGS_PLATELEGS_75(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torags platelegs 75"),
    TEMP_TORAGS_PLATEBODY_50(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torags platebody 50"),
    TEMP_TORAGS_PLATELEGS_50(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torags platelegs 50"),
    TEMP_TORAGS_PLATEBODY_25(ModItems.TORAGS_ARMOR.get(ArmorType.CHESTPLATE), "torags platebody 25"),
    TEMP_TORAGS_PLATELEGS_25(ModItems.TORAGS_ARMOR.get(ArmorType.LEGGINGS), "torags platelegs 25"),

    TEMP_KARILS_LEATHERTOP(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karils leathertop"),
    TEMP_KARILS_LEATHERSKIRT(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karils leatherskirt"),
    TEMP_KARILS_LEATHERTOP_100(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karils leathertop 100"),
    TEMP_KARILS_LEATHERSKIRT_100(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karils leatherskirt 100"),
    TEMP_KARILS_LEATHERTOP_75(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karils leathertop 75"),
    TEMP_KARILS_LEATHERSKIRT_75(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karils leatherskirt 75"),
    TEMP_KARILS_LEATHERTOP_50(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karils leathertop 50"),
    TEMP_KARILS_LEATHERSKIRT_50(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karils leatherskirt 50"),
    TEMP_KARILS_LEATHERTOP_25(ModItems.KARILS_ARMOR.get(ArmorType.CHESTPLATE), "karils leathertop 25"),
    TEMP_KARILS_LEATHERSKIRT_25(ModItems.KARILS_ARMOR.get(ArmorType.LEGGINGS), "karils leatherskirt 25"),

    BLUE_WIZARD_TOP(ModItems.BLUE_WIZARD_ROBES.get(ArmorType.CHESTPLATE), "blue wizard robe"),
    BLUE_WIZARD_BOTTOMS(ModItems.BLUE_WIZARD_ROBES.get(ArmorType.LEGGINGS), "blue skirt"),
    BLUE_WIZARD_TOP_T(ModItems.BLUE_WIZARD_ROBES_TRIM.get(ArmorType.CHESTPLATE), "blue wizard robe(t)"),
    BLUE_WIZARD_BOTTOMS_T(ModItems.BLUE_WIZARD_ROBES_TRIM.get(ArmorType.LEGGINGS), "blue skirt(t)"),
    BLUE_WIZARD_TOP_G(ModItems.BLUE_WIZARD_ROBES_GOLD.get(ArmorType.CHESTPLATE), "blue wizard robe(g)"),
    BLUE_WIZARD_BOTTOMS_G(ModItems.BLUE_WIZARD_ROBES_GOLD.get(ArmorType.LEGGINGS), "blue skirt(g)"),

    BLACK_WIZARD_TOP(ModItems.BLACK_WIZARD_ROBES.get(ArmorType.CHESTPLATE), "black robe"),
    BLACK_WIZARD_BOTTOMS(ModItems.BLACK_WIZARD_ROBES.get(ArmorType.LEGGINGS), "black skirt"),
    BLACK_WIZARD_TOP_T(ModItems.BLACK_WIZARD_ROBES_TRIM.get(ArmorType.CHESTPLATE), "black wizard robe(t)"),
    BLACK_WIZARD_BOTTOMS_T(ModItems.BLACK_WIZARD_ROBES_TRIM.get(ArmorType.LEGGINGS), "black skirt(t)"),
    BLACK_WIZARD_TOP_G(ModItems.BLACK_WIZARD_ROBES_GOLD.get(ArmorType.CHESTPLATE), "black wizard robe(g)"),
    BLACK_WIZARD_BOTTOMS_G(ModItems.BLACK_WIZARD_ROBES_GOLD.get(ArmorType.LEGGINGS), "black skirt(g)"),

    ELDER_CHAOS_ROBES_TOP(ModItems.ELDER_CHAOS_ROBES.get(ArmorType.CHESTPLATE), "elder chaos top"),
    ELDER_CHAOS_ROBES(ModItems.ELDER_CHAOS_ROBES.get(ArmorType.LEGGINGS), "elder chaos robe"),

    PINK_SKIRT_BOTTOMS(ModItems.PINK_SKIRT.get(ArmorType.LEGGINGS), "pink skirt"),

    MONKS_ROBES_TOP(ModItems.MONKS_ROBE.get(ArmorType.CHESTPLATE), "monks robe top"),
    MONKS_ROBES_BOTTOMS(ModItems.MONKS_ROBE.get(ArmorType.LEGGINGS), "monks robe bottom"),
    MONKS_ROBES_TOP_T(ModItems.MONKS_ROBE_TRIM.get(ArmorType.CHESTPLATE), "monk's robe top(t)"),
    MONKS_ROBES_BOTTOMS_T(ModItems.MONKS_ROBE_TRIM.get(ArmorType.LEGGINGS), "monk's robe bottom(t)"),
    MONKS_ROBES_TOP_G(ModItems.MONKS_ROBE_GOLD.get(ArmorType.CHESTPLATE), "monk's robe top(g)"),
    MONKS_ROBES_BOTTOMS_G(ModItems.MONKS_ROBE_GOLD.get(ArmorType.LEGGINGS), "monk's robe bottom(g)"),
    ZAMORAK_MONKS_ROBES_TOP(ModItems.ZAMORAK_MONK_ROBE.get(ArmorType.CHESTPLATE), "zamorak monk top"),
    ZAMORAK_MONKS_ROBES_BOTTOMS(ModItems.ZAMORAK_MONK_ROBE.get(ArmorType.LEGGINGS), "zamorak monk bottom"),

    PRIEST_GOWN_TOP(ModItems.PRIEST_GOWN_ROBES.get(ArmorType.CHESTPLATE), "priest gown top"),
    PRIEST_GOWN_BOTTOMS(ModItems.PRIEST_GOWN_ROBES.get(ArmorType.LEGGINGS), "priest gown bottom"),

    DRUIDS_ROBES_TOP(ModItems.DRUIDS_ROBES.get(ArmorType.CHESTPLATE), "druids robe top"),
    DRUIDS_ROBES_BOTTOMS(ModItems.DRUIDS_ROBES.get(ArmorType.LEGGINGS), "druids robe"),

    PURPLE_ROBES_TOP(ModItems.PURPLE_ROBES.get(ArmorType.CHESTPLATE), "purple robe top"),
    PURPLE_ROBES_BOTTOMS(ModItems.PURPLE_ROBES.get(ArmorType.LEGGINGS), "purple robe bottoms"),

    GREY_ROBES_TOP(ModItems.GREY_ROBES.get(ArmorType.CHESTPLATE), "grey robe top"),
    GREY_ROBES_BOTTOMS(ModItems.GREY_ROBES.get(ArmorType.LEGGINGS), "grey robe bottoms"),

    YELLOW_ROBES_TOP(ModItems.YELLOW_ROBES.get(ArmorType.CHESTPLATE), "yellow robe top"),
    YELLOW_ROBES_BOTTOMS(ModItems.YELLOW_ROBES.get(ArmorType.LEGGINGS), "yellow robe bottoms"),

    TEAL_ROBES_TOP(ModItems.TEAL_ROBES.get(ArmorType.CHESTPLATE), "teal robe top"),
    TEAL_ROBES_BOTTOMS(ModItems.TEAL_ROBES.get(ArmorType.LEGGINGS), "teal robe bottoms"),

    RED_ROBES_TOP(ModItems.RED_ROBES.get(ArmorType.CHESTPLATE), "red robe top"),
    RED_ROBES_BOTTOMS(ModItems.RED_ROBES.get(ArmorType.LEGGINGS), "red robe bottoms"),

    HAM_ROBES_TOP(ModItems.HAM_ROBES.get(ArmorType.CHESTPLATE), "ham shirt"),
    HAM_ROBES_BOTTOMS(ModItems.HAM_ROBES.get(ArmorType.LEGGINGS), "ham robe"),

    SNAKESKIN_BODY(ModItems.SNAKESKIN_ARMOR.get(ArmorType.CHESTPLATE), "snakeskin body"),
    SNAKESKIN_LEGS(ModItems.SNAKESKIN_ARMOR.get(ArmorType.CHESTPLATE), "snakeskin chaps"),
    SNAKESKIN_BOOTS(ModItems.SNAKESKIN_ARMOR.get(ArmorType.BOOTS), "snakeskin boots"),

    LEATHER_BODY(ModItems.LEATHER_ARMOR.get(ArmorType.CHESTPLATE), "leather body"),
    LEATHER_LEGS(ModItems.LEATHER_ARMOR.get(ArmorType.LEGGINGS), "leather chaps"),
    LEATHER_BODY_G(ModItems.LEATHER_GOLD_ARMOR.get(ArmorType.CHESTPLATE), "leather body(g)"),
    LEATHER_LEGS_G(ModItems.LEATHER_GOLD_ARMOR.get(ArmorType.LEGGINGS), "leather chaps(g)"),
    LEATHER_BODY_HARD(ModItems.LEATHER_HARD_ARMOR.get(ArmorType.CHESTPLATE), "hardleather body"),
    LEATHER_BOOTS(ModItems.LEATHER_ARMOR.get(ArmorType.BOOTS), "leather boots"),

    STUDDED_BODY(ModItems.STUDDED_ARMOR.get(ArmorType.CHESTPLATE), "studded body"),
    STUDDED_LEGS(ModItems.STUDDED_ARMOR.get(ArmorType.LEGGINGS), "studded chaps"),
    STUDDED_BODY_T(ModItems.STUDDED_TRIM_ARMOR.get(ArmorType.CHESTPLATE), "studded body(t)"),
    STUDDED_LEGS_T(ModItems.STUDDED_TRIM_ARMOR.get(ArmorType.LEGGINGS), "studded chaps(t)"),
    STUDDED_BODY_G(ModItems.STUDDED_GOLD_ARMOR.get(ArmorType.CHESTPLATE), "studded body(g)"),
    STUDDED_LEGS_G(ModItems.STUDDED_GOLD_ARMOR.get(ArmorType.LEGGINGS), "studded chaps(g)"),

    BLACK_DHIDE_BODY(ModItems.BLACK_DHIDE_ARMOR.get(ArmorType.CHESTPLATE), "black d'hide body"),
    BLACK_DHIDE_LEGS(ModItems.BLACK_DHIDE_ARMOR.get(ArmorType.LEGGINGS), "black d'hide chaps"),

    GREEN_DHIDE_BODY(ModItems.GREEN_DHIDE_ARMOR.get(ArmorType.CHESTPLATE), "green d'hide body"),
    GREEN_DHIDE_LEGS(ModItems.GREEN_DHIDE_ARMOR.get(ArmorType.LEGGINGS), "green d'hide chaps"),

    RED_DHIDE_BODY(ModItems.RED_DHIDE_ARMOR.get(ArmorType.CHESTPLATE), "red d'hide body"),
    RED_DHIDE_LEGS(ModItems.RED_DHIDE_ARMOR.get(ArmorType.LEGGINGS), "red d'hide chaps"),

    BLUE_DHIDE_BODY(ModItems.BLUE_DHIDE_ARMOR.get(ArmorType.CHESTPLATE), "blue d'hide body"),
    BLUE_DHIDE_LEGS(ModItems.BLUE_DHIDE_ARMOR.get(ArmorType.LEGGINGS), "blue d'hide chaps"),

    BUILDERS_COSTUME_BODY(ModItems.BUILDERS_COSTUME.get(ArmorType.CHESTPLATE), "builders shirt"),
    BUILDERS_COSTUME_LEGS(ModItems.BUILDERS_COSTUME.get(ArmorType.LEGGINGS), "builders trousers"),
    BUILDERS_COSTUME_BOOTS(ModItems.BUILDERS_COSTUME.get(ArmorType.BOOTS), "builders boots"),

    MYSTIC_ROBES_BLUE_TOP(ModItems.MYSTIC_ROBES_BLUE.get(ArmorType.CHESTPLATE), "mystic robe top blue"),
    MYSTIC_ROBES_BLUE_BOTTOMS(ModItems.MYSTIC_ROBES_BLUE.get(ArmorType.LEGGINGS), "mystic robe bottom blue");

    public final Item item;
    public final String name;

    OverrideArmors(AbstractArmorItem.RegisteredItem<? extends Item> item, String name) {
        this.item = item.get();
        this.name = name;
    }
}
