x:0
y:0.2
backgroundColor : 1258291200
hasFinished : false
hasAhrimDefeated : false
hasDharokDefeated : false
hasGuthanDefeated : false
hasKarilDefeated : false
hasToragDefeated : false
hasVeracDefeated : false
barrowsPoints : 0