small = false
osrs_screen = true
exp_tracker = true
thurgo = false
idle_alert = false
osrs_vertical = false
virtual_levels = false
osrs_style_inventory = false
dark_inventory_background = false
render_health = false
render_hotbar = false
render_experience_bar = false
render_map_overlay = true
protected_slot = false
persistent_mouse = true
farming_login_message = true
use_custom_armor = true
unrender_farming_armorstands = false
debug = false