small = false
osrs_screen = true
exp_tracker = true
thurgo = false
idle_alert = false
osrs_vertical = false
osrs_style_inventory = false
dark_inventory_background = false
render_health = false
render_hotbar = false
render_experience_bar = false
render_map_overlay = true
protected_slot = false
persistent_mouse = true
farming_login_message = true
use_custom_armor = true
unrender_farming_armorstands = false
scale = 1.0
debug = false
right_click_menu = true
agility_outlines = true
xp-tracker = true
scoreboard = true
armor_override = true
hp_prayer_bars = false
remove_branding = false
remove_food_tooltip = false
mob_highlight = false
force_resource_pack = true
slot_highlight = true
enable_browser = false
small_inventory = false
virtual_levels = false
custom_capes = true
reduce_crops = false
barrows_helper = true
target_info = true